name: build

on: [workflow_call, workflow_dispatch]

env:
  PACKAGE_NAME: linux-cachyos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Compute directory of package SHA256
        run: |
          cd ${{ env.PACKAGE_NAME }}
          hash=$(find . -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum)
          echo "PACKAGE_DIRECTORY_HASH=$hash" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: ../builder/cache
          key: ccache-${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_DIRECTORY_HASH }}
          restore-keys: |
            ccache-${{ env.PACKAGE_NAME }}
            ccache-

      - name: build Docker image
        working-directory: builder
        run: docker build . --file Dockerfile --tag ${{ github.repository }}:latest

      - name: run Docker image
        run: docker run -i -e GITHUB_KEY=${{ secrets.GITHUB_TOKEN }} -e REPO=${{ github.repository }} -e PKG=${{ env.PACKAGE_NAME }} -v "$(realpath ./cache)":/home/builder/.cache/ccache:Z ${{ github.repository }}:latest
